# Black code formatter configuration
[tool.black]
line-length = 100
target-version = ['py310']
extend-exclude = '''
/(
  # Directories to exclude
  \.venv
  | migrations
  | \.git
  | __pycache__
)/
'''

# isort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
skip_glob = [
    ".venv/*",
    "migrations/*"
]